### ISSUE TITLE
AwsCommunity::S3::BucketNotification

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/community-registry-extensions#1]
### Tracking Issue

One of the top requests in the [CloudFormation coverage roadmap repo](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap) is [AWS::S3::BucketNotification](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/79), a resource that would solve the well-documented circular dependency issue that prevents a notification configuration from being created at the same time as the bucket and the queue, topic, or function that is receiving the notification.

This resource is an attempt to solve that problem externally with a public registry extension. While ideally the resource would be created as an integral part of the `AWS::S3::Bucket` resource, solving it here can serve as an example of what is possible with third party resource types. We also need a resource to use as a pilot for our build and release process.

**Schema design**

- Id
- Events
- Filters
- BucketArn
- TargetArn
- TargetType

This resource differs from the original in that you only configure one notification at a time. The resource handles the SDK calls to configure all notifications for the bucket, making sure not to change or delete any of the pre-existing notifications. It also creates the necessary role for S3 to access the target.

**Sample template**

```yml
Resources:
  Queue:
    Type: AWS::SQS::Queue
  Bucket:
    Type: AWS::S3::Bucket
  Notification:
    Type: AwsCommunity::S3::BucketNotification
    Properties:
      Id: MyNotification
      Events:
        - s3:ObjectCreated:*
      Filters:
        - Name: suffix
          Value: gif
      BucketArn: !GetAtt Bucket.Arn
      TargetType: Queue
      TargetArn: !GetAtt Queue.Arn
    DependsOn:
      - Bucket
      - Queue
```

**Downsides**

This resource intentionally introduces drift by altering the notification configuration on the bucket.
