### ISSUE TITLE
CloudFront WebACLAssociation Resource

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/community-registry-extensions#39]
# AwsCommunity::CloudFront::WebACLAssociation Resource Tracking Issue

Adding a new resource that can be used to associated a WebACL to a CloudFront distribution, when the CloudFront distribution was created outside of the CloudFormation template. Currently, CloudFormation ‘AWS::WAFv2::WebACLAssociation’ resource has a limitation that a new WebACL provisioned using CloudFormation cannot be associated to an existing CloudFront distribution (created outside of the CloudFormation template). For associating a web ACL to resources in CloudFormation, we can create a resource ‘AWS::WAFv2::WebACLAssociation’. However, this resource type only supports below ResourceArn values for Application Load Balancer, API Gateway and AppSync GraphQL API. Please refer to below documentation link : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-webaclassociation.html

To address this, In the handler methods we make API calls to the CloudFront service and update the distribution configuration. The idea is to first fetch the current configuration of the CloudFront distribution by making the get_distribution_config API call , extract the etag value from the response (this value is required to perform the update Distribution API call), make required changes to the current configurations apply the new configuration to the CloudFront distribution by supplying the new configuration object, and etag value in the update_distribution API call.

Schema design

- Name
- DistributionArn
- WebAclArn
- Tags

Sample template
```yml
AWSTemplateFormatVersion: "2010-09-09"
Description: "This is to protect the CloudFront"
Parameters : 
  DistributionARN : 
    Type : String 
  WebAclARN : 
    Type : String 
Resources:
  CFwebACLAssociation:
    Type : AwsCommunity::CloudFront::WebACLAssociation
    Properties :
      DistributionArn: !Ref DistributionARN
      WebAclArn: !Ref WebAclARN
```

@greengangsta
