### ISSUE TITLE
AwsCommunity::Time::Sleep

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/community-registry-extensions#80]
### What type of extension are you looking for?

Resource

### Describe the extension you'd like to request

A resource that simply sleeps for X seconds. Sometimes resources aren't actually fully deployed when CloudFormation starts to deploy a dependent resource, and a sleep would solve it.

### Describe the solution you'd like

```
Resources:

  Sleep10:
    Type: AwsCommunity::Time::Sleep
    Properties:
      Seconds: 10
```

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change
